### ISSUE TITLE
Fix the path chdir hack in run command

### ISSUE THREAD

**Issue by hellais** [ooni/probe-cli#15]
Currently, due to a bug in measurement-kit: https://github.com/measurement-kit/measurement-kit/issues/1635, we use a workaround to avoid having file paths that contain utf-8 characters in them: https://github.com/ooni/probe-cli/blob/master/nettests/nettests.go#L70.

We should not forget to update this workaround when the bug in measurement-kit is fixed.

**Comment by hellais** [comment]
We actually ended up dealing with this at the probe-desktop side of things, see: https://github.com/ooni/probe-desktop/commit/d97189f312eff5462abeb56e34a2b9de36e6b51e

**Comment by bassosimone** [comment]
> [...] due to a bug in measurement-kit

I would actually call this a bug of Windows, or maybe just a bug of the times. Windows and Java were pioneers in supporting more rich encodings, and ended having the `char` / `wchar` split. Later built systems, or just systems that arrived later to the party, tend to use UTF-8. (For example, it is glorious that in Go a string can hold arbitrary bytes; while there is another language that basically broke the world in order to have a clean split between  bytes and string.)
